export default {
    arrow: require('./arrow.svg'),
    facebook: require('./facebook.svg'),
    image: require('./image.svg'),
    instagram: require('./instagram.svg'),
    link: require('./link.svg'),
    menu: require('./menu.svg'),
    pdf: require('./pdf.svg'),
    redpdf: require('./redpdf.svg'),
    rrs: require('./rrs.svg'),
    search: require('./search.svg'),
    telegram: require('./telegram.svg'),
    twitter: require('./twitter.svg'),
    user: require('./user.svg'),
    viewed: require('./viewed.svg'),
    filterArrow: require('./filter-arrow.svg'),
    exit: require('./exit.svg'),
    company: require('./company.svg'),
    workPosition: require('./work-position.svg'),
    email: require('./email.svg'),
    backArrow: require('./back-arrow.svg'),
    marker: require('./marker.svg'),
    blackFacebook: require('./black-facebook.svg'),
    blackInstagram: require('./black-instagram.svg'),
    blackTelegram: require('./black-telegram.svg'),
    blackYoutube: require('./black-youtube.svg')
};
